### ISSUE TITLE
New field for default cluster catalog GitRepo location in Tenant object

### ISSUE THREAD

**Issue by tobru** [projectsyn/lieutenant-operator#48]
Add a new field to the `Tenant` object to allow setting a default location for cluster catalog repositories and specify which secret will be used:

```
spec:
  clusterCatalogGitRepo:
    baseURL: ssh://git@git.example.net/syn/cluster-catalogs/
    apiSecretRef:
      name: git-example-credentials
```

This field can then be used by the API to figure out where the default location of cluster-catalog repositories are stored.

Example: `spec.clusterCatalogGitRepo.baseURL` could be set to `ssh://git@git.example.net/syn/cluster-catalogs/` which is then used by the API to set the corresponding field when creating a cluster without explicitly specifying a location for the cluster catalog git repository.

**Comment by corvus-ch** [comment]
I would go more on the line of a template and thus naming it `spec.clusterCataloGitRepoURLTemplate`. Variables like tenant, static facts and cluster ids can then be used to build up the effective URL of a cluster.

This assumes that this templating would also be possible to define on a global level and used as a default if not set on the `Tenant`.

Do we have potential need for other URL templates as well? In this case I would name the field `spec.URLTemplates.clusterCatalog`. This makes room to add more when needed.

**Comment by tobru** [comment]
I've amended the initial description of the issue to match the discussions in https://github.com/projectsyn/lieutenant-api/issues/42

**Comment by srueg** [comment]
To be discussed, should we specify a base URL or a template to be used?

1. Base URL (🚀):
```
spec:
  clusterCatalogGitRepos:
    baseURL: ssh://git@git.example.net/syn/cluster-catalogs/
    apiSecretRef:
      name: git-example-credentials
```

2. URL template (assuming [Go template](https://golang.org/pkg/text/template/)) (🎉):
```
spec:
  clusterCatalogGitRepos:
    urlTemplate: ssh://git@git.example.net/customer-a/cluster-catalogs/{{ .cluster_id }}.git
    apiSecretRef:
      name: git-example-credentials
```
Possible values which can be used in the template:
* `{{ .cluster_id }}`
* `{{ .tenant_id }}`
* Cluster facts `{{ .cluster_facts.cloud }}`
* Others?

Please vote with 🚀 for 1. or 🎉 for 2. and/or write a comment.

**Comment by simu** [comment]
I'm in favor of the template solution, since we've been talking about how the concept of a "baseURL" is confusing in Commodore.

**Comment by corvus-ch** [comment]
"baseURL" is not only confusing. It can also be restrictive and can make it impossible to apply a given scheme.

**Comment by srueg** [comment]
I just realized that we don't really need a URL template but rather `repoName` and `path` templates.
The URL was just a workaround to provide the name and path in a single string (via the API). The actual API host name needs to be provided in the credentials secret anyway.

```
spec:
  clusterCatalogGitRepoTemplate:
    path: customer-a/cluster-catalogs
    name: "{{ .cluster_id }}"
    apiSecretRef:
      name: git-example-credentials
```
This would also allow the `apiSecretRef` to be templated.
Additionally https://github.com/projectsyn/lieutenant-api/issues/41 should probably be implemented by the operator and not by the API.
